name: neuron-emodel-opt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - numpy=1.24.3
  - scipy=1.11.4
  - matplotlib=3.7.2
  - pandas=2.0.3
  - h5py=3.9.0
  - pyyaml=6.0.1
  - jsonschema=4.19.2
  - mpi4py=3.1.4
  - cython=3.0.5
  - setuptools=68.2.2
  - pip:
    - neuron==8.2.4
    - bluepyopt==1.14.18
    - bluepyefe==2.4.7
    - efel==5.6.8
    - singlecell-emodel-suite==0.2.0
    - git-lfs==1.6.0
variables:
  - NEURON_HOME: $CONDA_PREFIX
  - PYTHONPATH: $CONDA_PREFIX/lib/python/site-packages